#!/bin/bash

set -o nounset
set -o errexit

# Reset in case getopts has been used previously in the shell.
OPTIND=1

# Common operations
initialize() {
    down
    start
    install
    docker-compose ps
}

start() {
    docker-compose up -d --remove-orphans
    sleep 1
    docker-compose ps
}

install() {
    docker-compose exec front bash -c "yarn run build"
}

stop() {
    docker-compose stop
}

down() {
    docker-compose down --remove-orphans
}

serve() {
    docker-compose exec front bash -c "yarn run start"
}

# Usage info
show_help() {
cat << EOF
Usage:  ${0##*/} [COMMAND]

Commands:
  initialize       Start the project no matter what state it is in
  start            Start docker containers
  install          Run front app installation scripts
  stop             Stop docker containers
  down             Remove docker containers
  serve            Serve Angular files for local dev
EOF
}

# Get cli options
while getopts "he:" opt; do
  case $opt in
    h)
        show_help
        exit 0
        ;;
    e)
        env=".$OPTARG"
        ;;
    *)
        show_help >&2
        exit 1
        ;;
  esac
done

# Shift off the options and optional --.
shift "$((OPTIND-1))"

# Show help if no argument was supplied
if [ $# -eq 0 ]
  then
    show_help >&2
    exit 1
fi

case "$1" in
 initialize)
        initialize
        ;;
 start)
        start
        ;;
 stop)
        stop
        ;;
 down)
        down
        ;;
 restart)
        stop
        start
        ;;
 install)
        install
        ;;
 serve)
        serve
        ;;
 *)
        show_help >&2
        exit 1
esac

exit 0
